# Model Training

## Objective

The objective of this notebook is to train multiple machine learning regression models and compare their performance on the Ames Housing dataset.

The following models will be evaluated:

- Linear Regression
- Decision Tree Regressor
- Random Forest Regressor
- Gradient Boosting Regressor
- XGBoost Regressor

The best-performing model will be selected for hyperparameter tuning.

In [1]:
import joblib
import pandas as pd
import numpy as np 

from sklearn.linear_model import LinearRegression

from sklearn.tree import DecisionTreeRegressor

from sklearn.ensemble import (
    RandomForestRegressor,
    GradientBoostingRegressor
)

from xgboost import XGBRegressor

from sklearn.metrics import (
    mean_absolute_error,
    mean_squared_error,
    r2_score
)

In [2]:
# ==========================
# Load Models
# ==========================

# Encoded data (for tree models)
X_train_encoded = joblib.load("../models/X_train_encoded.pkl")
X_test_encoded = joblib.load("../models/X_test_encoded.pkl")

# Scaled data (for Linear Regression)
X_train_scaled = joblib.load("../models/X_train_scaled.pkl")
X_test_scaled = joblib.load("../models/X_test_scaled.pkl")

# Target
y_train = joblib.load("../models/y_train.pkl")
y_test = joblib.load("../models/y_test.pkl")

In [3]:
# Creating single evaluation function

def evaluate_model(y_true, predictions):

    mae = mean_absolute_error(y_true, predictions)
    mse = mean_squared_error(y_true, predictions)
    rmse = np.sqrt(mse)
    r2 = r2_score(y_true, predictions)

    return [mae, mse, rmse, r2]

In [4]:
# Linear Regression

linear = LinearRegression()

linear.fit(X_train_scaled, y_train)

linear_predictions = linear.predict(X_test_scaled)

linear_results = [
    mean_absolute_error(y_test, linear_predictions),
    mean_squared_error(y_test, linear_predictions),
    np.sqrt(mean_squared_error(y_test, linear_predictions)),
    r2_score(y_test, linear_predictions)
]

In [5]:
# Decision Tree Regressor

tree = DecisionTreeRegressor(random_state = 42)

tree.fit(X_train_encoded, y_train)

tree_predictions = tree.predict(X_test_encoded)

In [6]:
# Random Forest Regressor

forest = RandomForestRegressor(random_state = 42)

forest.fit(X_train_encoded, y_train)

forest_predictions = forest.predict(X_test_encoded)

In [7]:
# Gradient Boosting Regressor

gradient = GradientBoostingRegressor(random_state = 42)

gradient.fit(X_train_encoded, y_train)

gradient_predictions = gradient.predict(X_test_encoded)

In [8]:
# XGBoost Regressor

xgb = XGBRegressor(random_state = 42)

xgb.fit(X_train_encoded, y_train)

xgb_predictions = xgb.predict(X_test_encoded)

In [9]:
linear_results = evaluate_model(y_test, linear_predictions)
tree_results = evaluate_model(y_test, tree_predictions)
forest_results = evaluate_model(y_test, forest_predictions)
gradient_results = evaluate_model(y_test, gradient_predictions)
xgb_results = evaluate_model(y_test, xgb_predictions)

In [10]:
# ===========================
# Compare Models
# ===========================

results = pd.DataFrame({
    'Model': ["Linear Regression", "Decision Tree", "Random Forest", "Gradient Boosting", "XGBoost"],
    'MAE': [linear_results[0], tree_results[0], forest_results[0], gradient_results[0], xgb_results[0]],
    'MSE': [linear_results[1], tree_results[1], forest_results[1], gradient_results[1], xgb_results[1]],
    'RMSE': [linear_results[2], tree_results[2], forest_results[2], gradient_results[2], xgb_results[2]],
    'R2 Score': [linear_results[3], tree_results[3], forest_results[3], gradient_results[3], xgb_results[3]]
})

results

               Model            MAE           MSE           RMSE   R2 Score
0  Linear Regression  791943.524611  6.402214e+11  800138.363913 -82.467298
1      Decision Tree   25306.431507  1.587801e+09   39847.219120   0.792994
2      Random Forest   17706.682089  8.945700e+08   29909.363555   0.883373
3  Gradient Boosting   16546.014712  7.460834e+08   27314.526809   0.902731
4            XGBoost   17588.550781  7.797096e+08   27923.280037   0.898347

In [11]:
results.sort_values(by = "R2 Score", ascending = False)

               Model            MAE           MSE           RMSE   R2 Score
3  Gradient Boosting   16546.014712  7.460834e+08   27314.526809   0.902731
4            XGBoost   17588.550781  7.797096e+08   27923.280037   0.898347
2      Random Forest   17706.682089  8.945700e+08   29909.363555   0.883373
1      Decision Tree   25306.431507  1.587801e+09   39847.219120   0.792994
0  Linear Regression  791943.524611  6.402214e+11  800138.363913 -82.467298

### Hence, **Gradient Boosting** is the best model

In [12]:
# Best Model

best_model = gradient

In [13]:
# Saving and exporting the best model i.e. Gradient

joblib.dump(best_model, "../models/best_model.pkl")

['../models/best_model.pkl']

In [14]:
# Save comparison to csv

results.to_csv(
    "../reports/results/model_comparison.csv",
    index=False
)

# Conclusion

Five regression algorithms were trained and evaluated.

The models were compared using:

- Mean Absolute Error
- Mean Squared Error
- Root Mean Squared Error
- R² Score

The best-performing model i.e. **Gradient Boosting Regressor** was selected for hyperparameter tuning in the next notebook.