# Model Training

## Objective

The objective of this notebook is to train multiple machine learning regression models and compare their performance on the Ames Housing dataset.

The following models will be evaluated:

- Linear Regression
- Decision Tree Regressor
- Random Forest Regressor
- Gradient Boosting Regressor
- XGBoost Regressor

The best-performing model will be selected for hyperparameter tuning.

In [1]:
import joblib
import pandas as pd

from sklearn.linear_model import LinearRegression

from sklearn.tree import DecisionTreeRegressor

from sklearn.ensemble import (
    RandomForestRegressor,
    GradientBoostingRegressor
)

from xgboost import XGBRegressor

from sklearn.metrics import (
    mean_absolute_error,
    mean_squared_error,
    r2_score
)

In [2]:
# Load Models

X_train = joblib.load("../models/X_train.pkl")
X_test = joblib.load("../models/X_test.pkl")

y_train = joblib.load("../models/y_train.pkl")
y_test = joblib.load("../models/y_test.pkl")

In [3]:
# Creating single evaluation function

def evaluate_model(model):
    predictions = model.predict(X_test)

    mae = mean_absolute_error(y_test, predictions)
    mse = mean_squared_error(y_test, predictions)
    rmse = mse ** 0.5
    r2 = r2_score(y_test, predictions)

    return [mae, mse, rmse, r2]

In [4]:
# Linear Regression

linear = LinearRegression()

linear.fit(X_train, y_train)

linear_results = evaluate_model(linear)

In [5]:
# Decision Tree Regressor

tree = DecisionTreeRegressor(random_state = 42)

tree.fit(X_train, y_train)

tree_results = evaluate_model(tree)

In [6]:
# Random Forest Regressor

forest = RandomForestRegressor(random_state = 42)

forest.fit(X_train, y_train)

forest_results = evaluate_model(forest)

In [7]:
# Gradient Boosting Regressor

gradient = GradientBoostingRegressor(random_state = 42)

gradient.fit(X_train, y_train)

gradient_results = evaluate_model(gradient)

In [8]:
# XGBoost Regressor

xgb = XGBRegressor(random_state = 42)

xgb.fit(X_train, y_train)

xgb_results = evaluate_model(xgb)

In [9]:
# ===========================
# Compare Models
# ===========================

results = pd.DataFrame({
    'Model': ["Linear Regression", "Decision Tree", "Random Forest", "Gradient Boosting", "XGBoost"],
    'MAE': [linear_results[0], tree_results[0], forest_results[0], gradient_results[0], xgb_results[0]],
    'MSE': [linear_results[1], tree_results[1], forest_results[1], gradient_results[1], xgb_results[1]],
    'RMSE': [linear_results[2], tree_results[2], forest_results[2], gradient_results[2], xgb_results[2]],
    'R2 Score': [linear_results[3], tree_results[3], forest_results[3], gradient_results[3], xgb_results[3]]
})

results

               Model            MAE           MSE           RMSE   R2 Score
0  Linear Regression  791943.524611  6.402214e+11  800138.363913 -82.467298
1      Decision Tree   25271.376712  1.584210e+09   39802.139235   0.793462
2      Random Forest   17678.387637  8.951037e+08   29918.284121   0.883303
3  Gradient Boosting   16540.617636  7.460387e+08   27313.709241   0.902737
4            XGBoost   17588.550781  7.797096e+08   27923.280037   0.898347

In [10]:
results.sort_values(by = "R2 Score", ascending = False)

               Model            MAE           MSE           RMSE   R2 Score
3  Gradient Boosting   16540.617636  7.460387e+08   27313.709241   0.902737
4            XGBoost   17588.550781  7.797096e+08   27923.280037   0.898347
2      Random Forest   17678.387637  8.951037e+08   29918.284121   0.883303
1      Decision Tree   25271.376712  1.584210e+09   39802.139235   0.793462
0  Linear Regression  791943.524611  6.402214e+11  800138.363913 -82.467298

### Hence, **Gradient Boosting** is the best model

In [11]:
# Best Model

best_model = gradient

In [12]:
# Saving and exporting the best model i.e. Gradient

joblib.dump(best_model, "../models/best_model.pkl")

['../models/best_model.pkl']

In [13]:
# Save comparison to csv

results.to_csv(
    "../reports/results/model_comparison.csv",
    index=False
)

# Conclusion

Five regression algorithms were trained and evaluated.

The models were compared using:

- Mean Absolute Error
- Mean Squared Error
- Root Mean Squared Error
- R² Score

The best-performing model i.e. **Gradient Boosting Regressor** was selected for hyperparameter tuning in the next notebook.